### ISSUE TITLE
The file selector does not work in firefox

### ISSUE THREAD

**Issue by poi33** [enonic/app-cty-manager#25]
Uncaught (in promise) TypeError: window.showOpenFilePicker is not a function

Seems this is cutting edge and not fully supported: https://caniuse.com/?search=file%20access%20api

**Comment by reisfmb** [comment]
This was a known problem when I decided to go with the file system API following Thomas suggestion:
https://discuss.enonic.com/t/app-idea-content-type-manager/2610/13
I'm not sure if I agree with not having support for other browsers such as firefox as Tom answered. What do you think?
![image](https://user-images.githubusercontent.com/67838246/143240160-4d552875-ad9b-4222-84e7-4d926c23af31.png)

**Comment by poi33** [comment]
I think this is a terrbile idea to not have support for most browsers. 
But i now like 90% of the web use chrome 🤷 so this might be ok. 
We will need a warning if the browser does not support the api so, could you maybe add a warning if the api methods are not available?
